export const WATER_TRAVEL_RULES = Object.freeze({
  shallowWater: 'wade',
  deepWater: 'emergency-swim',
  shallowWaterSlowsMovement: true,
  waterConsumesStamina: true,
  zeroStaminaCausesDrowning: true,
  drowningSlowsAndDamages: true,
  aiPlansRoutineRoutesThroughDeepWater: false,
  emergencySwimTargetsNearestReachableLand: true,
  canWorkWhileSwimming: false,
  canFightWhileSwimming: false,
  canCarryHeavyCargoWhileSwimming: false,
  interIslandMigrationRequiresBoat: true,
  interIslandColonizationRequiresBoat: true,
  interIslandWarRequiresBoat: true,
  aquaticSpeciesIgnoreLandSwimLimits: true,
  landAnimalsSwimOnlyForEscapeOrShortCrossing: true,
  shoreFishingRemainsOnLand: true,
} as const);
