import { memo, useCallback, useEffect, useRef, useState } from 'react';
import ImagePreviewDialog from '@/components/ImagePreviewDialog';
import { cn } from '@/lib/utils';
import './markdown-styles.css';

interface MarkdownContentProps {
  content: string;
  className?: string;
  enableImagePreview?: boolean;
  imagePreviewTitle?: string;
}

interface MarkdownHtmlProps {
  content: string;
  className?: string;
  enableImagePreview: boolean;
  onPreviewImage: (payload: { src: string; title: string }) => void;
}

const MarkdownHtml = memo(function MarkdownHtml({
  content,
  className,
  enableImagePreview,
  onPreviewImage,
}: MarkdownHtmlProps) {
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!contentRef.current || !content) return;

    const codeBlocks = contentRef.current.querySelectorAll('pre');
    codeBlocks.forEach((pre) => {
      if (pre.querySelector('.copy-button')) return;

      const code = pre.querySelector('code');
      if (!code) return;

      const button = document.createElement('button');
      button.className =
        'copy-button absolute top-3 right-3 px-3 py-1.5 text-xs rounded-md bg-white/10 hover:bg-white/20 text-white/70 hover:text-white transition-all opacity-0 group-hover:opacity-100';
      button.textContent = 'Copy';
      button.onclick = () => {
        navigator.clipboard.writeText(code.textContent || '');
        button.textContent = 'Copied';
        setTimeout(() => {
          button.textContent = 'Copy';
        }, 2000);
      };

      pre.classList.add('group', 'relative');
      pre.appendChild(button);
    });
  }, [content]);

  const handleContentClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if (!enableImagePreview) return;
    const target = event.target as HTMLElement | null;
    if (!target) return;
    const image = target.closest('img');
    if (!(image instanceof HTMLImageElement)) return;
    const src = (image.getAttribute('src') || '').trim();
    if (!src) return;

    event.preventDefault();
    event.stopPropagation();
    const title = (image.getAttribute('alt') || '').trim() || '图片预览';
    onPreviewImage({ src, title });
  };

  useEffect(() => {
    if (!contentRef.current) return;
    const images = contentRef.current.querySelectorAll('img');
    images.forEach((img) => {
      if (enableImagePreview) {
        img.classList.add('previewable-image', 'cursor-zoom-in');
        img.setAttribute('title', img.getAttribute('title') || '点击预览');
      } else {
        img.classList.remove('previewable-image', 'cursor-zoom-in');
      }
    });
  }, [content, enableImagePreview]);

  return (
    <>
      <div
        ref={contentRef}
        className={cn('markdown-body', className)}
        onClick={handleContentClick}
        // biome-ignore lint/security/noDangerouslySetInnerHtml: content is generated by trusted markdown renderer on the app side.
        dangerouslySetInnerHTML={{ __html: content }}
      />
    </>
  );
});

MarkdownHtml.displayName = 'MarkdownHtml';

export const MarkdownContent = memo(function MarkdownContent({
  content,
  className,
  enableImagePreview = false,
  imagePreviewTitle,
}: MarkdownContentProps) {
  const [previewOpen, setPreviewOpen] = useState(false);
  const [previewSrc, setPreviewSrc] = useState('');
  const [previewTitle, setPreviewTitle] = useState('');

  const handlePreviewImage = useCallback(
    (payload: { src: string; title: string }) => {
      setPreviewSrc(payload.src);
      setPreviewTitle(payload.title || imagePreviewTitle || '图片预览');
      setPreviewOpen(true);
    },
    [imagePreviewTitle],
  );

  return (
    <>
      <MarkdownHtml
        content={content}
        className={className}
        enableImagePreview={enableImagePreview}
        onPreviewImage={handlePreviewImage}
      />
      <ImagePreviewDialog
        open={previewOpen}
        src={previewSrc}
        title={previewTitle}
        onOpenChange={setPreviewOpen}
      />
    </>
  );
});

MarkdownContent.displayName = 'MarkdownContent';
