import type { ClimberLevelDefinition } from '../types';

export const TOGETHER_SKY_ASCENT_LEVEL: ClimberLevelDefinition = {
  id: 'together-sky-ascent',
  name: '在一起登顶',
  description:
    '单张大地图：主路径以模型跳台为主（管道、木板、货柜、斜坡、横杆），仅保留少量中继平台保证可达性。',
  startPosition: [0, 1.3, 0],
  cameraOffset: [0, 5.2, 10.4],
  theme: {
    skyColor: '#bfefff',
    floorColor: '#d9f2ff',
    gridPrimaryColor: '#8cc9e8',
    gridSecondaryColor: '#b7e2f5',
    sunColor: '#fff8d2',
  },
  platforms: [
    { id: 'start', size: [14, 1, 14], position: [0, 0, 0], color: '#f6d365' },
    { id: 'checkpoint-1', size: [6.2, 1, 5.2], position: [12, 12, 3.8], color: '#fbbf24' },
    { id: 'checkpoint-2', size: [6.4, 1, 5.4], position: [20, 24, 3], color: '#38bdf8' },
    { id: 'checkpoint-3', size: [6, 1, 5], position: [28, 34, -1], color: '#a78bfa' },
    { id: 'goal', size: [7.2, 1, 6], position: [26, 44, -5], color: '#6ee7b7' },
  ],
  setPieces: [
    {
      id: 'sp001',
      assetId: 'container_short',
      position: [6, 0.5, 1],
      solid: true,
      color: '#2b6dd6',
    },
    { id: 'sp002', assetId: 'plank_long', position: [9.1, 2, 2.2], solid: true, color: '#ad6f43' },
    {
      id: 'sp003',
      assetId: 'pipe_long',
      position: [12.2, 2.1, 3.7],
      solid: true,
      color: '#bccad4',
    },
    {
      id: 'sp004',
      assetId: 'beam_hazard',
      position: [15.3, 4, 4.1],
      solid: true,
      color: '#f1be2b',
      colliderInset: 0.86,
    },
    {
      id: 'sp005',
      assetId: 'round_stool',
      position: [17.9, 4.3, 2.5],
      solid: true,
      color: '#f26e53',
    },
    {
      id: 'sp006',
      assetId: 'ramp_wedge',
      position: [20.2, 5.1, 0.8],
      solid: true,
      color: '#b99f6b',
    },
    {
      id: 'sp007',
      assetId: 'container_long',
      position: [22.6, 5.9, -1.1],
      solid: true,
      color: '#d36435',
    },
    {
      id: 'sp008',
      assetId: 'plank_long',
      position: [25.4, 7.4, -3],
      solid: true,
      color: '#ae7448',
    },
    {
      id: 'sp009',
      assetId: 'pipe_long',
      position: [22.8, 7.5, -4.9],
      solid: true,
      color: '#bcc9d4',
    },
    {
      id: 'sp010',
      assetId: 'beam_hazard',
      position: [19.7, 9.1, -4.2],
      solid: true,
      color: '#f1be2b',
      colliderInset: 0.86,
    },
    {
      id: 'sp011',
      assetId: 'round_stool',
      position: [17.2, 9.4, -2.4],
      solid: true,
      color: '#eb6048',
    },
    {
      id: 'sp012',
      assetId: 'ramp_wedge',
      position: [15.3, 10.2, 0.1],
      solid: true,
      color: '#c0a777',
    },
    {
      id: 'sp013',
      assetId: 'plank_long',
      position: [13.5, 11.5, 2.1],
      solid: true,
      color: '#b1784c',
    },

    {
      id: 'sp014',
      assetId: 'container_short',
      position: [14.8, 12.6, 5.2],
      solid: true,
      color: '#2262c9',
    },
    {
      id: 'sp015',
      assetId: 'plank_long',
      position: [17.7, 14, 7.6],
      solid: true,
      color: '#b37a4d',
    },
    {
      id: 'sp016',
      assetId: 'pipe_long',
      position: [20.7, 14.1, 8.8],
      solid: true,
      color: '#c0ccd5',
    },
    {
      id: 'sp017',
      assetId: 'beam_hazard',
      position: [23.8, 15.8, 8],
      solid: true,
      color: '#f1be2b',
      colliderInset: 0.86,
    },
    {
      id: 'sp018',
      assetId: 'round_stool',
      position: [26.5, 16.1, 6.2],
      solid: true,
      color: '#ea6047',
    },
    {
      id: 'sp019',
      assetId: 'ramp_wedge',
      position: [28.3, 17, 4.2],
      solid: true,
      color: '#bca272',
    },
    {
      id: 'sp020',
      assetId: 'container_long',
      position: [26.4, 17.8, 1.8],
      solid: true,
      color: '#cd5930',
    },
    {
      id: 'sp021',
      assetId: 'plank_long',
      position: [23.6, 19.3, 1],
      solid: true,
      color: '#aa6f42',
    },
    {
      id: 'sp022',
      assetId: 'pipe_long',
      position: [21.2, 19.4, 2.8],
      solid: true,
      color: '#bcc9d3',
    },
    {
      id: 'sp023',
      assetId: 'beam_hazard',
      position: [20, 21.1, 5],
      solid: true,
      color: '#f1be2b',
      colliderInset: 0.86,
    },
    {
      id: 'sp024',
      assetId: 'round_stool',
      position: [21.8, 21.4, 7],
      solid: true,
      color: '#ef6950',
    },
    {
      id: 'sp025',
      assetId: 'ramp_wedge',
      position: [20.6, 22.6, 5.2],
      solid: true,
      color: '#c1a97a',
    },

    {
      id: 'sp026',
      assetId: 'container_short',
      position: [22.4, 24.6, 4.1],
      solid: true,
      color: '#2e6fd6',
    },
    {
      id: 'sp027',
      assetId: 'plank_long',
      position: [25.5, 26, 5.6],
      solid: true,
      color: '#b57b4d',
    },
    {
      id: 'sp028',
      assetId: 'pipe_long',
      position: [28.5, 26.1, 6.8],
      solid: true,
      color: '#bfccd5',
    },
    {
      id: 'sp029',
      assetId: 'beam_hazard',
      position: [31, 27.8, 5.7],
      solid: true,
      color: '#f1be2b',
      colliderInset: 0.86,
    },
    {
      id: 'sp030',
      assetId: 'round_stool',
      position: [32.8, 28.2, 3.7],
      solid: true,
      color: '#f06950',
    },
    {
      id: 'sp031',
      assetId: 'ramp_wedge',
      position: [33.2, 29, 1.2],
      solid: true,
      color: '#bea676',
    },
    {
      id: 'sp032',
      assetId: 'container_long',
      position: [31.2, 29.8, -1],
      solid: true,
      color: '#cf5c33',
    },
    {
      id: 'sp033',
      assetId: 'plank_long',
      position: [28.4, 31.2, -2],
      solid: true,
      color: '#ab7345',
    },
    {
      id: 'sp034',
      assetId: 'pipe_long',
      position: [25.8, 31.3, -0.8],
      solid: true,
      color: '#c0cbd6',
    },
    {
      id: 'sp035',
      assetId: 'beam_hazard',
      position: [24.7, 33, 1.2],
      solid: true,
      color: '#f1be2b',
      colliderInset: 0.86,
    },
    {
      id: 'sp036',
      assetId: 'round_stool',
      position: [26.8, 33.3, -0.8],
      solid: true,
      color: '#f36d54',
    },

    {
      id: 'sp037',
      assetId: 'ramp_wedge',
      position: [29.6, 34.8, -2.8],
      solid: true,
      color: '#c2ab7b',
    },
    {
      id: 'sp038',
      assetId: 'container_short',
      position: [31.6, 35.6, -4.8],
      solid: true,
      color: '#2568cf',
    },
    {
      id: 'sp039',
      assetId: 'plank_long',
      position: [29.5, 37, -6.8],
      solid: true,
      color: '#ae7346',
    },
    {
      id: 'sp040',
      assetId: 'pipe_long',
      position: [26.9, 37.1, -7.9],
      solid: true,
      color: '#bcc8d2',
    },
    {
      id: 'sp041',
      assetId: 'beam_hazard',
      position: [24.3, 38.8, -7.2],
      solid: true,
      color: '#f1be2b',
      colliderInset: 0.86,
    },
    {
      id: 'sp042',
      assetId: 'round_stool',
      position: [22.3, 39.1, -5.8],
      solid: true,
      color: '#ea6048',
    },
    { id: 'sp043', assetId: 'ramp_wedge', position: [23, 40, -3.8], solid: true, color: '#bfa878' },
    {
      id: 'sp044',
      assetId: 'container_long',
      position: [24.8, 40.8, -3],
      solid: true,
      color: '#cf5a33',
    },
    {
      id: 'sp045',
      assetId: 'plank_long',
      position: [26.8, 42.2, -4.7],
      solid: true,
      color: '#b57949',
    },
    {
      id: 'sp046',
      assetId: 'round_stool',
      position: [27.2, 42.7, -6.4],
      solid: true,
      color: '#f6735b',
    },

    {
      id: 'ground-road-1',
      assetId: 'road_segment',
      position: [0, -0.49, -14],
      solid: false,
      color: '#42454b',
    },
    {
      id: 'ground-road-2',
      assetId: 'road_segment',
      position: [8.8, -0.49, -14],
      solid: false,
      color: '#3d4046',
    },
    {
      id: 'ground-road-3',
      assetId: 'road_segment',
      position: [-8.8, -0.49, -14],
      solid: false,
      color: '#44484f',
    },
    {
      id: 'ground-road-4',
      assetId: 'road_segment',
      position: [17.6, -0.49, -14],
      solid: false,
      color: '#3f4349',
    },
    {
      id: 'ground-road-5',
      assetId: 'road_segment',
      position: [-17.6, -0.49, -14],
      solid: false,
      color: '#484c52',
    },

    { id: 'ground-tree-1', assetId: 'tree_pine', position: [-20, -0.5, 18], solid: false },
    { id: 'ground-tree-2', assetId: 'tree_pine', position: [-14, -0.5, 24], solid: false },
    { id: 'ground-tree-3', assetId: 'tree_pine', position: [19, -0.5, 20], solid: false },
    { id: 'ground-tree-4', assetId: 'tree_pine', position: [24, -0.5, 14], solid: false },
    { id: 'ground-tree-5', assetId: 'tree_pine', position: [28, -0.5, -2], solid: false },

    { id: 'ground-grass-1', assetId: 'grass_patch', position: [-10, -0.5, 12], solid: false },
    {
      id: 'ground-grass-2',
      assetId: 'grass_patch',
      position: [-6, -0.5, 15],
      solid: false,
      scale: [1.2, 1, 1.2],
    },
    {
      id: 'ground-grass-3',
      assetId: 'grass_patch',
      position: [7, -0.5, 14],
      solid: false,
      scale: [1.1, 1, 1.1],
    },
    { id: 'ground-grass-4', assetId: 'grass_patch', position: [12, -0.5, 17], solid: false },
    { id: 'ground-grass-5', assetId: 'grass_patch', position: [18, -0.5, 10], solid: false },
    { id: 'ground-grass-6', assetId: 'grass_patch', position: [22, -0.5, 6], solid: false },
  ],
};
