-- +goose Up
ALTER TABLE resources
  ADD COLUMN IF NOT EXISTS source_kind VARCHAR(24) NOT NULL DEFAULT '';

ALTER TABLE resources
  ADD COLUMN IF NOT EXISTS source_url VARCHAR(500) NOT NULL DEFAULT '';

ALTER TABLE resources
  ADD COLUMN IF NOT EXISTS license VARCHAR(32) NOT NULL DEFAULT '';

ALTER TABLE resources
  ADD COLUMN IF NOT EXISTS download_allowed BOOLEAN NOT NULL DEFAULT FALSE;
