-- +goose Up
ALTER TABLE ai_prompts
  ADD COLUMN IF NOT EXISTS tags TEXT,
  ADD COLUMN IF NOT EXISTS source_url VARCHAR(1000),
  ADD COLUMN IF NOT EXISTS source_author VARCHAR(200),
  ADD COLUMN IF NOT EXISTS source_license VARCHAR(100),
  ADD COLUMN IF NOT EXISTS imported_at TIMESTAMPTZ;
