import type { ClimberSetPieceAssetId } from './types';

export const REMOVED_SETPIECE_ASSET_IDS: ReadonlySet<ClimberSetPieceAssetId> = new Set([
  'round_stool',
  'grass_patch',
  'tree_pine',
  'road_segment',
  'boulder_round',
  'stump_short',
  'log_tilt',
  'branch_bridge',
  'pillar_thin',
  'ledge_hook',
  'stepping_stone',
  'rope_post',
  'hut_frame_small',
  'hut_frame_large',
  'arch_gate',
  'tunnel_frame',
  'cube_frame',
  'house_tunnel',
  'beam_cross',
  'cloud_pad',
  'cloud_ring',
  'cloud_arch',
  'floating_island',
  'spiral_pillar',
  'sky_bridge_long',
  'prism_gate',
  'lotus_pad',
  'meteor_chunk',
  'neon_pillar',
  'drum_platform',
  'zigzag_beam',
  'fan_blade',
  'bridge_arc',
  'crystal_cluster',
  'moon_step',
  'star_frame',
  'barrel_tower',
  'totem_mask',
  'shell_ridge',
  'wing_platform',
  'vortex_ring',
  'tower_gate',
  'hex_pad',
  'bridge_lattice',
  'orb_podium',
  'dune_backbone',
]);

export function isRemovedSetPieceAsset(assetId: ClimberSetPieceAssetId): boolean {
  return REMOVED_SETPIECE_ASSET_IDS.has(assetId);
}
