"""Preserve supplied CAMP PNGs and audit alpha before lossless runtime trimming."""
import argparse
import hashlib
import json
from pathlib import Path
import zipfile

from PIL import Image, ImageDraw

PROJECT = Path(__file__).resolve().parents[1]
ASSETS = PROJECT / "assets/ui/camp_hud_2_0"
OUTPUT = PROJECT / "test-output/camp-hud-2"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("archive", type=Path)
    args = parser.parse_args()
    OUTPUT.mkdir(parents=True, exist_ok=True)
    (OUTPUT / ".gdignore").touch()
    (ASSETS / "source").mkdir(parents=True, exist_ok=True)
    (ASSETS / "source/.gdignore").touch()
    rows = []
    with zipfile.ZipFile(args.archive) as archive:
        assert archive.testzip() is None
        for entry in archive.infolist():
            if not entry.filename.endswith(".png"):
                continue
            path = (ASSETS / "source" / entry.filename).resolve()
            assert path.is_relative_to((ASSETS / "source").resolve())
            data = archive.read(entry)
            if path.exists():
                assert path.read_bytes() == data, f"Source differs: {path}"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            with Image.open(path) as original:
                original.load()
                alpha = original.convert("RGBA").getchannel("A")
                bounds = {str(level): alpha.point(lambda a: 255 if a >= level else 0).getbbox()
                          for level in [1, 8, 32, 128, 250]}
                rows.append({"file": entry.filename, "size": original.size, "mode": original.mode,
                             "alpha_range": alpha.getextrema(), "alpha_bounds": bounds,
                             "sha256": hashlib.sha256(data).hexdigest()})
    runtime = ASSETS / "runtime"
    manifest = {}
    mapping = ["# CAMP HUD 2.0 素材映射", "", "44 张源 PNG 保留原字节。视觉边界采用 Alpha ≥ 8；裁切额外保留 4 原生像素，颜色与分辨率不重采样。Alpha ≥ 1 的边界及各阈值均见 JSON。", "",
               "| 文件 | 原始尺寸 | Alpha ≥ 1 边界 | 视觉边界 ≥ 8 | 用途 / 配置 |", "|---|---|---|---|---|"]
    for row in rows:
        source = ASSETS / "source" / row["file"]
        number = int(source.stem.split("_")[2])
        category = ("icons" if number >= 200 else "timeline" if number in (10, 11) else
                    "states" if number in (31, 32, 33, 41, 42, 43, 44, 71, 72, 82, 83, 84, 91, 92, 93) else
                    "buttons" if number in (30, 70, 90, 94) else "slots" if number in (40, 81) else "panels")
        bounds = row["alpha_bounds"]["8"]
        crop = (max(0, bounds[0]-4), max(0, bounds[1]-4), min(row["size"][0], bounds[2]+4), min(row["size"][1], bounds[3]+4))
        target = runtime / category / (source.stem.lower() + ".png")
        target.parent.mkdir(parents=True, exist_ok=True)
        with Image.open(source) as original:
            original.crop(crop).save(target)
        import_file = target.with_suffix(".png.import")
        if import_file.exists():
            import_file.write_text(import_file.read_text(encoding="utf-8").replace("mipmaps/generate=false", "mipmaps/generate=true"), encoding="utf-8")
        nine = number in (1, 10, 20, 40, 41, 42, 43, 50, 52, 60, 61, 70, 71, 72, 80, 81, 82, 83, 84)
        usage = "NinePatch / 保留角与边" if nine else "Overlay / 固定比例" if number == 44 else "系统 Icon / 固定比例" if number >= 200 else "TextureRect / 固定比例"
        row.update(runtime=target.relative_to(PROJECT).as_posix(), runtime_crop=crop, visual_bounds=bounds,
                   nine_patch=nine, fixed_aspect=not nine, state_overlay=number==44, system_icon=number>=200, usage=usage)
        manifest[number] = "res://" + row["runtime"]
        mapping.append(f'| {row["file"]} | {row["size"]} | {row["alpha_bounds"]["1"]} | {bounds} | {usage} |')
    # Reuse the supplied detail sheet's paper edges and blue field, excluding all
    # baked placeholder bars, sample buttons and the sample gameplay icon.
    details = ASSETS / "source/Pack_A/CAMP_UI_050_survivor_detail_panel.png"
    for number, name, crop in [(501, "detail_paper_border", (76, 633, 1028, 1360)),
                               (502, "detail_paper_fill", (175, 971, 550, 1030)),
                               (503, "detail_header", (104, 168, 632, 322))]:
        target = runtime / "panels" / (name + ".png")
        with Image.open(details) as original:
            original.crop(crop).save(target)
        manifest[number] = "res://" + target.relative_to(PROJECT).as_posix()
        mapping.append(f'| 050 派生 {name} | 原生裁切 {crop} | — | — | ' + ("NinePatch 边框，draw_center=false" if number == 501 else "纸张填充 / 蓝色 Header") + ' |')
    (PROJECT / "ui/camp").mkdir(exist_ok=True)
    entries = ",\n".join(f'\t{key}: "{value}"' for key, value in manifest.items())
    (PROJECT / "ui/camp/camp_asset_manifest.gd").write_text('extends RefCounted\n## Generated by art/import_camp_hud.py; source pixels stay unmodified.\nconst PATHS: Dictionary = {\n' + entries + '\n}\n', encoding="utf-8")
    (PROJECT / "art/CAMP_HUD_ASSET_MAP.md").write_text("\n".join(mapping)+"\n", encoding="utf-8")
    report = {"archive": args.archive.name, "archive_sha256": hashlib.sha256(args.archive.read_bytes()).hexdigest(),
              "png_count": len(rows), "pngs": rows}
    (PROJECT / "art/CAMP_HUD_ASSET_AUDIT.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    for page, start in enumerate(range(0, len(rows), 15)):
        sheet = Image.new("RGB", (1500, 1000), "#607585")
        draw = ImageDraw.Draw(sheet)
        for i, row in enumerate(rows[start:start + 15]):
            x, y = (i % 5) * 300, (i // 5) * 330
            with Image.open(ASSETS / "source" / row["file"]) as original:
                art = original.convert("RGBA")
                art.thumbnail((284, 270))
                sheet.paste(art, (x + (300-art.width)//2, y + (280-art.height)//2), art)
            draw.text((x+5,y+280), Path(row["file"]).stem[8:], fill="white")
            draw.text((x+5,y+299), f'{row["size"]} A32={row["alpha_bounds"]["32"]}', fill="white")
        sheet.save(OUTPUT / f"source-contact-{page+1}.png")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
